version: '3'

services:
  redis-1:
    image: redis:latest
    container_name: redisnode-1
    command: redis-server --port 6379 --cluster-enabled yes --appendonly yes
    ports:
      - "6379"
    networks:
      - redis-cluster

  redis-2:
    image: redis:latest
    container_name: redisnode-2
    command: redis-server --port 6379 --cluster-enabled yes --appendonly yes
    ports:
      - "6380"
    networks:
      - redis-cluster

  redis-3:
    image: redis:latest
    container_name: redisnode-3
    command: redis-server --port 6379 --cluster-enabled yes --appendonly yes
    ports:
      - "6381"
    networks:
      - redis-cluster

networks:
  redis-cluster:
    driver: bridge
